saka/urls.py
from django.urls import path
from saka import views

app_name = "saka"
urlpatterns = [
    path('', views.index, name='index'),
    path("signin", views.signin,name='signin'),
    path("labpage", views.labpage,name='labpage'),
    path("formB", views.formB,name='formB'),
    path("report", views.report,name='report'),
    path("test", views.test,name='test'),
    path("log_out", views.log_out,name='log_out'),
]

sakalab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('saka.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saka/models.py
from django.db import models


class Analyte(models.Model):
    analyte_name = models.CharField(max_length=30)
    department = models.TextField()
    accdev = models.FloatField(db_column='AccDEV')  # Field name made lowercase.
    tea = models.FloatField(db_column='TEa')  # Field name made lowercase.
    unit = models.CharField(max_length=30)
    up = models.IntegerField()
    down = models.IntegerField()

    class Meta:
        # managed = False
        db_table = 'analyte'


class Cash(models.Model):
    laboratoryid = models.IntegerField(db_column='laboratoryID')  # Field name made lowercase.
    analyteid = models.IntegerField(db_column='analyteID')  # Field name made lowercase.
    department = models.IntegerField()
    date = models.DateField(blank=True, null=True)
    kittype = models.IntegerField(blank=True, null=True)
    testmethod = models.IntegerField(blank=True, null=True)
    devicetype = models.IntegerField(blank=True, null=True)
    latnumber = models.CharField(max_length=300, blank=True, null=True)
    analytecv = models.FloatField(db_column='analyteCV', blank=True, null=True)  # Field name made lowercase.
    testresult = models.FloatField(db_column='testResult', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        # managed = False
        db_table = 'cash'

    def __str__(self):
        return '%s,%s,%s,%s,%s' % (self.laboratoryid, self.analyteid, self.department, self.date,self.testresult)


class Device(models.Model):
    devicename = models.CharField(max_length=50)
    department = models.CharField(max_length=30)

    class Meta:
        # managed = False
        db_table = 'device'


class Devicecompany(models.Model):
    companyname = models.CharField(db_column='Companyname', max_length=50)  # Field name made lowercase.
    department = models.CharField(max_length=30)

    class Meta:
        # managed = False
        db_table = 'devicecompany'


class Facttable(models.Model):
    laboratoryid = models.IntegerField(db_column='laboratoryID')  # Field name made lowercase.
    analyteid = models.IntegerField(db_column='analyteID')  # Field name made lowercase.
    department = models.IntegerField()
    date = models.DateField()
    kittype = models.IntegerField()
    testmethod = models.IntegerField()
    devicetype = models.IntegerField()
    latnumber = models.CharField(max_length=300)
    analytecv = models.FloatField(db_column='analyteCV')  # Field name made lowercase.
    testresult = models.FloatField(db_column='testResult')  # Field name made lowercase.

    class Meta:
        # managed = False
        db_table = 'facttable'


class Info(models.Model):
    laboratoryid = models.IntegerField(db_column='laboratoryID')  # Field name made lowercase.
    analyteid = models.IntegerField(db_column='analyteID')  # Field name made lowercase.
    department = models.IntegerField()
    date = models.DateField()
    kittype = models.IntegerField()
    testmethod = models.IntegerField()
    devicetype = models.IntegerField()
    latnumber = models.CharField(max_length=300)
    analytecv = models.FloatField(db_column='analyteCV')  # Field name made lowercase.
    testresult = models.FloatField(db_column='testResult')  # Field name made lowercase.
    mean = models.FloatField(db_column='Mean', blank=True, null=True)  # Field name made lowercase.
    bias = models.FloatField(db_column='Bias', blank=True, null=True)  # Field name made lowercase.
    sd = models.FloatField(db_column='SD', blank=True, null=True)  # Field name made lowercase.
    adjmean = models.FloatField(db_column='adjMean', blank=True, null=True)  # Field name made lowercase.
    adjsd = models.FloatField(db_column='adjSD', blank=True, null=True)  # Field name made lowercase.
    cv = models.FloatField(blank=True, null=True)
    dev = models.FloatField(db_column='DEV', blank=True, null=True)  # Field name made lowercase.
    sdi = models.FloatField(db_column='SDI', blank=True, null=True)  # Field name made lowercase.
    um = models.FloatField(db_column='Um', blank=True, null=True)  # Field name made lowercase.
    n = models.IntegerField(db_column='N')  # Field name made lowercase.

    class Meta:
        # managed = False
        db_table = 'info'


class InfoDevice(models.Model):
    laboratoryid = models.IntegerField(db_column='laboratoryID')  # Field name made lowercase.
    analyteid = models.IntegerField(db_column='analyteID')  # Field name made lowercase.
    department = models.IntegerField()
    date = models.DateField()
    kittype = models.IntegerField()
    testmethod = models.IntegerField()
    devicetype = models.IntegerField()
    latnumber = models.CharField(max_length=300)
    analytecv = models.FloatField(db_column='analyteCV')  # Field name made lowercase.
    testresult = models.FloatField(db_column='testResult')  # Field name made lowercase.
    mean = models.FloatField(db_column='Mean', blank=True, null=True)  # Field name made lowercase.
    bias = models.FloatField(db_column='Bias', blank=True, null=True)  # Field name made lowercase.
    sd = models.FloatField(db_column='SD', blank=True, null=True)  # Field name made lowercase.
    adjmean = models.FloatField(db_column='adjMean', blank=True, null=True)  # Field name made lowercase.
    adjsd = models.FloatField(db_column='adjSD', blank=True, null=True)  # Field name made lowercase.
    cv = models.FloatField(blank=True, null=True)
    dev = models.FloatField(db_column='DEV', blank=True, null=True)  # Field name made lowercase.
    sdi = models.FloatField(db_column='SDI', blank=True, null=True)  # Field name made lowercase.
    um = models.FloatField(db_column='Um', blank=True, null=True)  # Field name made lowercase.
    n = models.IntegerField(db_column='N')  # Field name made lowercase.

    class Meta:
        # managed = False
        db_table = 'info_device'


class InfoTD(models.Model):
    laboratoryid = models.IntegerField(db_column='laboratoryID')  # Field name made lowercase.
    analyteid = models.IntegerField(db_column='analyteID')  # Field name made lowercase.
    department = models.IntegerField()
    date = models.DateField()
    kittype = models.IntegerField()
    testmethod = models.IntegerField()
    devicetype = models.IntegerField()
    latnumber = models.CharField(max_length=300)
    analytecv = models.FloatField(db_column='analyteCV')  # Field name made lowercase.
    testresult = models.FloatField(db_column='testResult')  # Field name made lowercase.
    mean = models.FloatField(db_column='Mean', blank=True, null=True)  # Field name made lowercase.
    bias = models.FloatField(db_column='Bias', blank=True, null=True)  # Field name made lowercase.
    sd = models.FloatField(db_column='SD', blank=True, null=True)  # Field name made lowercase.
    adjmean = models.FloatField(db_column='adjMean', blank=True, null=True)  # Field name made lowercase.
    adjsd = models.FloatField(db_column='adjSD', blank=True, null=True)  # Field name made lowercase.
    cv = models.FloatField(blank=True, null=True)
    dev = models.FloatField(db_column='DEV', blank=True, null=True)  # Field name made lowercase.
    sdi = models.FloatField(db_column='SDI', blank=True, null=True)  # Field name made lowercase.
    um = models.FloatField(db_column='Um', blank=True, null=True)  # Field name made lowercase.
    n = models.IntegerField(db_column='N')  # Field name made lowercase.

    class Meta:
        # managed = False
        db_table = 'info_t_d'


class InfoTmethod(models.Model):
    laboratoryid = models.IntegerField(db_column='laboratoryID')  # Field name made lowercase.
    analyteid = models.IntegerField(db_column='analyteID')  # Field name made lowercase.
    department = models.IntegerField()
    date = models.DateField()
    kittype = models.IntegerField()
    testmethod = models.IntegerField()
    devicetype = models.IntegerField()
    latnumber = models.CharField(max_length=300)
    analytecv = models.FloatField(db_column='analyteCV')  # Field name made lowercase.
    testresult = models.FloatField(db_column='testResult')  # Field name made lowercase.
    mean = models.FloatField(db_column='Mean', blank=True, null=True)  # Field name made lowercase.
    bias = models.FloatField(db_column='Bias', blank=True, null=True)  # Field name made lowercase.
    sd = models.FloatField(db_column='SD', blank=True, null=True)  # Field name made lowercase.
    adjmean = models.FloatField(db_column='adjMean', blank=True, null=True)  # Field name made lowercase.
    adjsd = models.FloatField(db_column='adjSD', blank=True, null=True)  # Field name made lowercase.
    cv = models.FloatField(blank=True, null=True)
    dev = models.FloatField(db_column='DEV', blank=True, null=True)  # Field name made lowercase.
    sdi = models.FloatField(db_column='SDI', blank=True, null=True)  # Field name made lowercase.
    um = models.FloatField(db_column='Um', blank=True, null=True)  # Field name made lowercase.
    n = models.IntegerField(db_column='N')  # Field name made lowercase.

    class Meta:
        # managed = False
        db_table = 'info_tmethod'


class Laboratory(models.Model):
    lab_id = models.AutoField(primary_key=True)
    laboratory_name = models.CharField(max_length=100)
    username = models.CharField(max_length=30)
    pass_field = models.CharField(db_column='pass',
                                  max_length=32)  # Field renamed because it was a Python reserved word.
    role = models.CharField(max_length=50)
    phnuber = models.CharField(max_length=12)
    email = models.CharField(max_length=255)
    province = models.CharField(db_column='Province', max_length=300)  # Field name made lowercase.
    city = models.CharField(db_column='City', max_length=300)  # Field name made lowercase.

    class Meta:
        # managed = False
        db_table = 'laboratory'


class Latnumber(models.Model):
    latnumber = models.CharField(max_length=300)

    class Meta:
        # managed = False
        db_table = 'latnumber'

saka/forms.py
from django import forms
from . import models


class Cash_form(forms.ModelForm):
    class Meta:
        model = models.Cash
        fields = '__all__'

saka/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect
from django.http import HttpResponse ,QueryDict
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from . import models
from .serializers import *
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from . import forms
from .extra_Functions import *


def log_out(request):
    logout(request)
    return redirect('saka:signin')


def index(request):
    logout(request)
    return render(request, 'saka/index.html')


def signin(request):
    logout(request)
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # ...
            user = form.get_user()
            login(request, user)
            return redirect('saka:labpage')
    else:
        form = AuthenticationForm()
    return render(request, 'saka/signin.html', {'form': form})


@login_required(login_url="/signin")
def labpage(request):
    user_lab_informations = Laboratory_info(request)
    try:
        user_lab_name = user_lab_informations['laboratory_name']
    except:
        user_lab_name = 'not lab found!'
    return render(request, 'saka/labpage.html', context={'user_lab_name': user_lab_name})


def test(request):
    print(old_days_data(request))
    return render(request, 'saka/test.html')


def formB(request):
    if request.method == "POST":
        a = QueryDict.get(request.POST,'search')
        # if a :
        print(QueryDict.get(request.POST,'day'))
        return redirect('saka:formB')
    else:
        context = {'old_days_data': old_days_data(request),
                   'backdate': old_days_data(request)[3],
                   'locfilde': 1,
                   'Latnumbers_info': Latnumbers_info(),
                   'selected_lat': Latnumbers_info()[0],
                   'Analyte_info': Analyte_info(),
                   'formcache': formcash(),
                   'Device_info': Device_info(request),
                   'Tmethod_info': Tmethod_info(request),
                   'Devicecompany_info': Devicecompany_info(request),
                   }
    return render(request, 'saka/formB.html', context=context)


@login_required(login_url="/signin")
def report(request):
    return render(request, 'saka/Report.html')

saka/templates/saka/formB.html
{% extends 'saka/header.html' %}
{% load static %}
{% load saka_extras %}

{% block extra %}
    <title>بارگذاری بیوشیمی | سامانه ارزیابی کیفیت آزمایشگاه‌ها</title>
    <link rel="stylesheet" href="{% static 'saka/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'saka/css/bootstrap-theme.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'saka/css/jquery.Bootstrap-PersianDateTimePicker.css' %}"/>
    <script type="text/javascript" src="{% static 'saka/js/jquery-3.1.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'saka/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript">
        $('#input1').change(function () {
            var $this = $(this),
                value = $this.val();
            alert(value);
        });
        $('#textbox1').change(function () {
            var $this = $(this),
                value = $this.val();
            alert(value);
        });
        $('[data-name="disable-button"]').click(function () {
            $('[data-mddatetimepicker="true"][data-targetselector="#input1"]').MdPersianDateTimePicker('disable', true);
        });
        $('[data-name="enable-button"]').click(function () {
            $('[data-mddatetimepicker="true"][data-targetselector="#input1"]').MdPersianDateTimePicker('disable', false);
        });
    </script>
    <script type="text/javascript" src="{% static 'saka/js/jalaali.js' %}"></script>
    <script src="{% static 'saka/js/jquery.Bootstrap-PersianDateTimePicker.js' %}" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script>
        $('body').on('keydown', 'input, select', function (e) {
            if (e.key === "Enter") {
                var self = $(this), form = self.parents('form:eq(0)'), focusable, next;
                focusable = form.find('input,a,select,button,textarea').filter(':visible');
                next = focusable.eq(focusable.index(this) + 1);
                if (next.length) {
                    next.focus();
                } else {
                    form.submit();
                }
                return false;
            }
            if (e.keyCode === 40) {
                var self = $(this), form = self.parents('form:eq(0)'), focusable, next;
                focusable = form.find('input,a,select,button,textarea').filter(':visible');
                next = focusable.eq(focusable.index(this) + 5);
                if (next.length) {
                    next.focus();
                } else {
                    form.submit();
                }
                return false;
            }
            if (e.keyCode === 38) {
                var self = $(this), form = self.parents('form:eq(0)'), focusable, next;
                focusable = form.find('input,a,select,button,textarea').filter(':visible');
                next = focusable.eq(focusable.index(this) - 5);
                if (next.length) {
                    next.focus();
                } else {
                    form.submit();
                }
                return false;
            }
            if (e.keyCode === 37) {
                var self = $(this), form = self.parents('form:eq(0)'), focusable, next;
                focusable = form.find('input,a,select,button,textarea').filter(':visible');
                next = focusable.eq(focusable.index(this) + 1);
                if (next.length) {
                    next.focus();
                } else {
                    form.submit();
                }
                return false;
            }
            if (e.keyCode === 39) {
                var self = $(this), form = self.parents('form:eq(0)'), focusable, next;
                focusable = form.find('input,a,select,button,textarea').filter(':visible');
                next = focusable.eq(focusable.index(this) - 1);
                if (next.length) {
                    next.focus();
                } else {
                    form.submit();
                }
                return false;
            }
        });
    </script>
    <style>
        .disabledform {
            color: #f3da00 !important;
        }
    </style>
    <script>
        var locfilde =
        {{ locfilde }}
        var disabledform = function () {
            if (locfilde) {
                $('.disabledid').prop('disabled', false);
            } else {
                $('.disabledid').prop('disabled', 'disabled').addClass('disabledform');
            }
        };
        $(disabledform);
        $(".disabledid").change(disabledform);

    </script>
    <script>
        $(function () {
            $("#kittypeglucose").change(function () {
                $("div.kittype select").val($("#kittypeglucose").val());
            });
        });
        $(function () {
            $("#devicetypeglucose").change(function () {
                $("div.devicetype select").val($("#devicetypeglucose").val());
            });
        });
    </script>
{% endblock %}

{% block main %}
    <form action={% url 'saka:formB' %} method="POST" id="date" class="upload-archive">
        {% csrf_token %}
        <label for='day'>داده های قبلی</label>
        <div>
            <input type="submit" id="search" name="search" value="جستجو" style="height: auto!important;">
            <select type="int" name="day" id="day">
                {% for day in old_days_data %}
                    <option value={{ day }}   {% if day == backdate %}selected{% endif %}>{{ day }}</option>
                {% endfor %}
            </select>
        </div>
    </form>

    <form action={% url 'saka:formB' %} method="POST" class="uploadform" id="base">
        {% csrf_token %}
        <h2 class="upload-title">فرم ورود اطلاعات آزمایشات بیوشیمی</h2>
        <div class="columnstyle">
            <div class="form-control">
                <div class="latnumber">
                    <label for='latnumber'>LOT number</label>
                    <select style="background-size: auto" type="int" name="latnumber" class="disabledid">
                        {% for lat in Latnumbers_info %}
                            <option value={{ lat }}   {% if lat == selected_lat %}selected{% endif %}>{{ lat }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-control columntitle">
                <span>نتیجه تست</span>
                <span>CV</span>
                <span>نام دستگاه</span>
                <span>شیوه آزمایش</span>
                <span>شرکت سازنده کیت</span>
            </div>
            {% for ky,value in Analyte_info.items %}
                {% with ANID=ky anname=value.analyte_name d_t="devicetype"|add:value.analyte_name|lower|cut:" " t_m="testmethod"|add:value.analyte_name|lower|cut:" " k_t="kittype"|add:value.analyte_name|lower|cut:" " cvid='cv'|add:value.analyte_name|lower|cut:" " unit=value.unit up=value.up down=value.down %}

                    <div class="form-control">
                        <div class="formbox">
                            <span>{{ '('|add:unit|add:')'|add:anname }}</span>
                            <input type="number" step="0.0001" min={{ down }}max={{ up }} id={{ anname }}
                                    name={{ anname }} placeholder="Enter{{ anname }}" autocomplete="off"
                                   class="disabledid"
                                    {% for id,dic in formcache.items %}
                                        {% if id == ANID %}
                                            value= {{ dic|get_item:'testresult' }}
                                        {% endif %}
                                    {% endfor %}
                            >
                        </div>
                        <div class="formbox">
                            <input type="int" step="0.0001" id={{ cvid }} name= {{ cvid }} placeholder=""
                                   autocomplete="off" class="disabledid"
                                    {% for id,dic in formcache.items %}
                                        {% if id == ANID %}
                                            value= {{ dic|get_item:'analytecv' }}
                                        {% endif %}
                                    {% endfor %}
                            >
                        </div>
                        <div class="devicebox">
                            <div class="devicetype">
                                <select type="int" name={{ d_t }} id={{ d_t }} class="disabledid">
                                    <option value="...">...</option>
                                    {% for ky,value in Device_info.items %}
                                        <option value={{ ky }}
                                                        {% for id,dic in formcache.items %}
                                                            {% if id == ANID and dic|get_item:'devicetype' and ky == id %}
                                                                selected
                                                            {% endif %}
                                                        {% endfor %}
                                        >{{ value.devicename }}</option>
                                    {% endfor %}
                                </select>
                                <script type="application/json" name={{ d_t }} data-nonempty="">{}</script>
                            </div>
                        </div>
                        <div class="devicebox tmbox">
                            <select type="int" name={{ t_m }} id={{ t_m }} class="disabledid">
                                <option value="...">...</option>
                                {% for ky,value in Tmethod_info.items %}
                                    <option value={{ ky }}
                                                    {% for id,dic in formcache.items %}
                                                        {% if id == ANID and dic|get_item:'testmethod' and ky == id %}
                                                            selected
                                                        {% endif %}
                                                    {% endfor %}
                                    >{{ value.methodname }}</option>
                                {% endfor %}
                            </select>
                            <script type="application/json" name={{ t_m }} data-nonempty="">{}</script>
                        </div>
                        <div class="devicebox tmbox">
                            <div class="kittype">
                                <select type="int" name={{ k_t }} id={{ k_t }} class="disabledid">
                                    <option value="...">...</option>
                                    {% for ky,value in Devicecompany_info.items %}
                                        <option value={{ ky }}
                                                        {% for id,dic in formcache.items %}
                                                            {% if id == ANID and dic|get_item:'kittype' and ky == id %}
                                                                selected
                                                            {% endif %}
                                                        {% endfor %}
                                        >{{ value.companyname }}</option>
                                    {% endfor %}
                                </select>
                                <script type="application/json" name={{ k_t }} data-nonempty="">{}</script>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
        </div>

        <div class="form-control uploadsubmit">
            <input type="submit" name="save" value="save" {% if locfilde == 0 %} disabled
                   style='background-color: #666;border-color: #666;color: #ffffff4d;'{% endif %} >
            <input type="submit" name="send" value="send" {% if locfilde == 0 %} disabled
                   style='background-color: #666;border-color: #666;color: #ffffff4d;'{% endif %} >
        </div>
    </form>
{% endblock %}

saka/templates/saka/header.html
<!doctype html>{% load static %}<head>    <link rel="stylesheet" href="{% static 'saka/css/style.css' %}">    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">    <link rel="shortcut icon" href="{% static 'saka/css/tlogo.png' %}" type="image/x-icon">    <meta content="width=device-width, initial-scale=1" name="viewport"/>    <script type="text/javascript">        function showHeaderList() {            var element = document.getElementById("header-list");            element.classList.add("showheaderlist");        }        function hideHeaderList() {            var element = document.getElementById("header-list");            element.classList.remove("showheaderlist");        }    </script>    {% block extra %}    {% endblock %}</head><body><div class="lab-header">    <a href="labpage.php"><img src="{% static 'saka/css/h-Logos.png' %}"></a>    <i class="material-icons openlist" onclick="showHeaderList()">menu</i>    <ul class="header-list" id="header-list">        <li class="material-icons closelist" onclick="hideHeaderList()">close</li>        <li><a href="{% url 'saka:labpage' %}">صفحه اصلی</a></li>        <li class="hedaer-upload"><a>بارگذاری</a>            <ul class="dropdownlist">                <li class="listparent"><a href={% url 'saka:formB' %} >بیوشیمی</a></li>                <li class="listparent"><a href="formHM.php">هماتولوژی</a></li>                <li class="listparent"><a href="formHO.php">ایمنولوژی و هورمون شناسی</a></li>            </ul>        </li>        <li class="hedaer-report"><a href="{% url 'saka:test' %}">گزارش گیری</a></li>        <li><a class="logout" href="#">آموزش</a></li>        <li><a class="logout" href="{% url 'saka:log_out' %}">خروج </a></li>    </ul></div>{% block main %}{% endblock %}</body></html>

saka/templates/saka/labpage.html
{% extends 'saka/header.html' %}

<style>
    p {
        margin-top: 250px;
        display: block;
        color: white;
        font-weight: bolder;
        font-size: 30px;
        border-bottom: 2px solid white;
        padding: 25px 0;
        width: 40%;
        margin: 0 auto;
    }

    @media only screen and (max-width: 768px) {
        p {
            padding: 5px 0;
            width: 80%;
        }
    }
</style>

{% block extra %}
    <title>ساکا | سامانه ارزیابی کیفیت آزمایشگاه‌ها</title>
{% endblock %}

{% block main %}
    <h2 style="text-align:center;margin-top: 15%;"><p>
        {#        ازمایشگاه#}
        {{ user_lab_name }}
        <br>"خوش آمدید"</p>
    </h2>
{% endblock %}

saka/templates/saka/signin.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'saka/css/style.css' %}">
    <title>ساکا | سامانه ارزیابی کیفیت آزمایشگاه ها</title>
    <link rel="shortcut icon" href="{% static 'saka/css/tlogo.png' %}" type="image/x-icon">
    <style>
        a:link, a:visited {
            background-color: rgba(0, 152, 222, 0.18);
            color: rgba(25, 178, 255, 0.62);

            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            border-radius: 20px;
            display: inline-block;
        }

        a:hover, a:active {
            background-color: rgba(0, 152, 222, 0.18);
            color: rgba(25, 178, 255, 0.99);
        }
        #formlogin label,ul{
            display: none;
        }
        #formlogin li{
            color: red;
            margin-bottom: 10px;
        }
    </style>
</head>
<body class="login">
    <div class="login-box">
        <div class="login-form" id="formpo">
            <img src="{% static 'saka/css/logos.png' %}" class="Login-logo">
            <form action={% url 'saka:signin' %} method="post" id="formlogin">
             {% csrf_token %}

{#                    <input required id="id_username" name="username" type="text" placeholder="نام کاربری"/>#}
{#                    <input required id="id_password" name="password" type="password" placeholder="رمز عبور"/>#}
                    {{form}}
                {% if form.errors %}
                    <h4>نام کاربری یا رمز عبور اشتباه است.</h4>
                {% endif %}
                <div class="login-submit">
                    <input type="submit" value="ورود"/>
                </div>
                <h4><a href="{% url 'saka:index' %}">صفحه اصلی</a></h4>
            </form>
        </div>
        <img src="{% static 'saka/css/lbox.jpg' %}" class="lbox">
    </div>


</body>
</html>

saka/templates/saka/test.html
{% extends 'saka/header.html' %}

{% block main %}
    {% if form %}
{#        {% for i in form %}#}
{#            <p>{{ i }}</p>#}
{#        {% endfor %}#}
        {{ form }}
    {% endif %}
{% endblock %}